name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations.
      # Consider changing this to true when your workflow is stable.
      fail-fast: false

      # configuration matrix
      matrix:
        os: [windows-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            qthost: 'windows'
            qtarch: 'win64_mingw'
            aqtTools: 'tools_mingw1310'
            cmake_defs: '-DWIN32=ON'
            artifact: 'qmsc.windows.zip'
            appdir: 'qmsc'

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.1'
        target: 'desktop'
        host: ${{ matrix.qthost }}
        arch: ${{ matrix.qtarch }}
        tools: ${{ matrix.aqtTools }}
        add-tools-to-path: true

    - name: Checkout
      uses: actions/checkout@v6
      with:
        lfs: true

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "install-output-dir=${{ github.workspace }}/dist" >> "$GITHUB_OUTPUT"
        echo "install-app-dir=${{ github.workspace }}/dist/${{ matrix.appdir }}" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -Wno-dev -G "Ninja Multi-Config"
        -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}
        ${{ matrix.cmake_defs }}

    - name: Build
      run: >
        cmake --build ${{ steps.strings.outputs.build-output-dir }}
        --config ${{ matrix.build_type }}

    - name: Install
      run: >
        cmake --install ${{ steps.strings.outputs.build-output-dir }}
        --config ${{ matrix.build_type }}
        --prefix ${{ steps.strings.outputs.install-app-dir }}

    - name: Package (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install libfuse2
        wget -nv -c https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x ./appimagetool-x86_64.AppImage
        ARCH=x86_64 ./appimagetool-x86_64.AppImage ${{ steps.strings.outputs.install-app-dir }} ${{ steps.strings.outputs.install-output-dir }}/${{ matrix.artifact }}

    - name: Create Code Signing Certificate (Windows)
      shell: pwsh
      if: matrix.os == 'windows-latest'
      run: |
        echo "${{ secrets.WIN_CERT_PFX }}" | out-file -encoding ascii cert.pfx.b64
        certutil -decode cert.pfx.b64 cert.pfx
        dir "C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\x64"
        dir "C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64"
        dir "C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x64"
        dir "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x64"
        dir "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64"
        dir "C:\Program Files (x86)\Windows Kits\10\bin\x64"

    - name: Sign Executable (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: >
        "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe" sign
        /f "cert.pfx"
        /p "${{ secrets.WIN_CERT_PASSWORD }}"
        /t http://timestamp.digicert.com
        /fd sha256 /td sha256
        /v "${{ steps.strings.outputs.install-app-dir }}\bin\qmsc.exe"

    - name: Package (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd ${{ steps.strings.outputs.install-output-dir }}
        7z a -tzip ${{ matrix.artifact }} ${{ steps.strings.outputs.install-app-dir }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      if: github.ref_type != 'tag'
      with:
        path: ${{ steps.strings.outputs.install-output-dir }}/${{ matrix.artifact }}
        archive: false

    - name: Release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        files: |
          ${{ steps.strings.outputs.install-output-dir }}/${{ matrix.artifact }}

